services:
  dokuwiki:
    image: basictheprogram/crossfire-dokuwiki:devel-2025.05.14a
    # image: dokuwiki-devel
    container_name: crossfire-dokuwiki
    user: "0:0"
    restart: unless-stopped

    environment:
      TZ: ${TZ}
      PHP_TIMEZONE: ${TZ}
      PHP_MEMORYLIMIT: ${PHP_MEMORYLIMIT}
      PHP_UPLOADLIMIT: ${PHP_UPLOADLIMIT}

    volumes:
      - ./storage:/storage

    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail-with-body", "http://localhost:8080/health.php"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    logging:
      driver: syslog
      options:
        syslog-address: ${SYSLOG_ADDRESS}
        syslog-format: "rfc5424"
        tag: "{{.Name}}"
        env: "HOSTNAME"

    ports:
      - "8080:8080"

    labels:
      - traefik.enable=true
      # Allow HTTP and HTTPS
      - traefik.http.routers.dokuwiki-http.rule=Host(`${DOMAIN2}`)
      - traefik.http.routers.dokuwiki-http.entrypoints=http
      - traefik.http.routers.dokuwiki-http.service=dokuwiki-service
      # Enable HTTPS
      - traefik.http.routers.dokuwiki-https.rule=Host(`${DOMAIN2}`)
      - traefik.http.routers.dokuwiki-https.entrypoints=https
      - traefik.http.routers.dokuwiki-https.tls=true
      - traefik.http.routers.dokuwiki-https.tls.certresolver=le
      - traefik.http.routers.dokuwiki-https.service=dokuwiki-service
      # Redirect all other HTTP traffic to HTTPS
      - traefik.http.routers.dokuwiki-http-redir.rule=Host(`${DOMAIN2}`)
      - traefik.http.routers.dokuwiki-http-redir.entrypoints=http
      - traefik.http.routers.dokuwiki-http-redir.middlewares=https-redirect@docker
      # Define the backend service
      - traefik.http.services.dokuwiki-service.loadbalancer.server.port=8080

    networks:
      - nexxus

networks:
  nexxus:
    name: nexxus
    driver: bridge
    external: true

# Testing change .env SYSLOG_ADDRESS="tcp://127.0.0.1:514"
#
# docker run -d --name syslog-ng -p 514:514 balabit/syslog-ng
