services:
  dokuwiki:
#    image: dokuwiki/dokuwiki:stable
    image: dokuwiki/dokuwiki:oldstable
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PHP_TIMEZONE: America/Chicago
      PHP_MEMORYLIMIT: 128M
      PHP_UPLOADLIMIT: 128M
    volumes:
      - ./storage:/storage
