---
services:
  vscode:
    container_name: dokuwiki-vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        UV_VERSION: latest
        DEBIAN_VERSION: bookworm
    volumes:
      - ..:/workspace:cached
    environment:
      TZ: ${TZ:-America/Chicago}
    command: sleep infinity
    networks:
      - nexxus

networks:
  nexxus:
    name: nexxus
    driver: bridge
